version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - automerge
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major
